/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonHTMLType, ButtonShape, ButtonType, Loading } from "./components/button/buttonHelpers";
import { unknown as SizeType } from "./components.d";
import { MouseEventHandler } from "react";
import { SizeType as SizeType1, ThemeConfig } from "./components/config-provider/context";
import { Locale } from "./components/locale";
import { Properties as CSSProperties } from "csstype";
import { SpinSize } from "./components/spin/Spin";
export { ButtonHTMLType, ButtonShape, ButtonType, Loading } from "./components/button/buttonHelpers";
export { unknown as SizeType } from "./components.d";
export { MouseEventHandler } from "react";
export { SizeType as SizeType1, ThemeConfig } from "./components/config-provider/context";
export { Locale } from "./components/locale";
export { Properties as CSSProperties } from "csstype";
export { SpinSize } from "./components/spin/Spin";
export namespace Components {
    interface BeesButton {
        "beeTitle": string;
        "block": boolean;
        "danger": boolean;
        "disabled": boolean;
        "ghost": boolean;
        "href": string;
        "htmlType": ButtonHTMLType;
        "icon": string;
        "loading": Loading;
        "prefixCls": string;
        "shape": ButtonShape;
        "size": SizeType;
        "target": string;
        "type": ButtonType;
    }
    interface BeesButtonGroup {
    }
    interface BeesConfigProvider {
        "componentSize": SizeType1;
        "locale": Locale;
        "theme": ThemeConfig;
    }
    interface BeesLayout {
        "beTagName": string;
        "hasSider": boolean;
        "prefixCls": string;
    }
    interface BeesLayoutContent {
        "beTagName": string;
        "hasSider": boolean;
        "prefixCls": string;
    }
    interface BeesLayoutFooter {
        "beTagName": string;
        "hasSider": boolean;
        "prefixCls": string;
    }
    interface BeesLayoutHeader {
        "beTagName": string;
        "hasSider": boolean;
        "prefixCls": string;
    }
    interface BeesLayoutSider {
        "breakpoint": 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl';
        "collapsed": boolean;
        "collapsedWidth": number | string;
        "collapsible": boolean;
        "defaultCollapsed": boolean;
        "prefixCls": string;
        "reverseArrow": boolean;
        "theme": 'light' | 'dark';
        "trigger": any;
        "width": number | string;
        "zeroWidthTriggerStyle": CSSProperties;
    }
    interface BeesLocaleProvider {
        "locale": Locale | undefined;
    }
    interface BeesSpace {
    }
    interface BeesSpin {
        "delay": number;
        "indicator": any;
        "prefixCls": string;
        "size": SpinSize;
        "spinning": boolean;
        "tip": any;
        "wrapperClassName": string;
    }
}
export interface BeesButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBeesButtonElement;
}
export interface BeesLayoutSiderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBeesLayoutSiderElement;
}
declare global {
    interface HTMLBeesButtonElementEventMap {
        "beeClick": MouseEventHandler;
        "beeMousedown": MouseEventHandler;
    }
    interface HTMLBeesButtonElement extends Components.BeesButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBeesButtonElementEventMap>(type: K, listener: (this: HTMLBeesButtonElement, ev: BeesButtonCustomEvent<HTMLBeesButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBeesButtonElementEventMap>(type: K, listener: (this: HTMLBeesButtonElement, ev: BeesButtonCustomEvent<HTMLBeesButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBeesButtonElement: {
        prototype: HTMLBeesButtonElement;
        new (): HTMLBeesButtonElement;
    };
    interface HTMLBeesButtonGroupElement extends Components.BeesButtonGroup, HTMLStencilElement {
    }
    var HTMLBeesButtonGroupElement: {
        prototype: HTMLBeesButtonGroupElement;
        new (): HTMLBeesButtonGroupElement;
    };
    interface HTMLBeesConfigProviderElement extends Components.BeesConfigProvider, HTMLStencilElement {
    }
    var HTMLBeesConfigProviderElement: {
        prototype: HTMLBeesConfigProviderElement;
        new (): HTMLBeesConfigProviderElement;
    };
    interface HTMLBeesLayoutElement extends Components.BeesLayout, HTMLStencilElement {
    }
    var HTMLBeesLayoutElement: {
        prototype: HTMLBeesLayoutElement;
        new (): HTMLBeesLayoutElement;
    };
    interface HTMLBeesLayoutContentElement extends Components.BeesLayoutContent, HTMLStencilElement {
    }
    var HTMLBeesLayoutContentElement: {
        prototype: HTMLBeesLayoutContentElement;
        new (): HTMLBeesLayoutContentElement;
    };
    interface HTMLBeesLayoutFooterElement extends Components.BeesLayoutFooter, HTMLStencilElement {
    }
    var HTMLBeesLayoutFooterElement: {
        prototype: HTMLBeesLayoutFooterElement;
        new (): HTMLBeesLayoutFooterElement;
    };
    interface HTMLBeesLayoutHeaderElement extends Components.BeesLayoutHeader, HTMLStencilElement {
    }
    var HTMLBeesLayoutHeaderElement: {
        prototype: HTMLBeesLayoutHeaderElement;
        new (): HTMLBeesLayoutHeaderElement;
    };
    interface HTMLBeesLayoutSiderElementEventMap {
        "beesBreakpoint": { broken: boolean };
        "beesCollapse": { collapsed: boolean; type: 'clickTrigger' | 'responsive' };
    }
    interface HTMLBeesLayoutSiderElement extends Components.BeesLayoutSider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBeesLayoutSiderElementEventMap>(type: K, listener: (this: HTMLBeesLayoutSiderElement, ev: BeesLayoutSiderCustomEvent<HTMLBeesLayoutSiderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBeesLayoutSiderElementEventMap>(type: K, listener: (this: HTMLBeesLayoutSiderElement, ev: BeesLayoutSiderCustomEvent<HTMLBeesLayoutSiderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBeesLayoutSiderElement: {
        prototype: HTMLBeesLayoutSiderElement;
        new (): HTMLBeesLayoutSiderElement;
    };
    interface HTMLBeesLocaleProviderElement extends Components.BeesLocaleProvider, HTMLStencilElement {
    }
    var HTMLBeesLocaleProviderElement: {
        prototype: HTMLBeesLocaleProviderElement;
        new (): HTMLBeesLocaleProviderElement;
    };
    interface HTMLBeesSpaceElement extends Components.BeesSpace, HTMLStencilElement {
    }
    var HTMLBeesSpaceElement: {
        prototype: HTMLBeesSpaceElement;
        new (): HTMLBeesSpaceElement;
    };
    interface HTMLBeesSpinElement extends Components.BeesSpin, HTMLStencilElement {
    }
    var HTMLBeesSpinElement: {
        prototype: HTMLBeesSpinElement;
        new (): HTMLBeesSpinElement;
    };
    interface HTMLElementTagNameMap {
        "bees-button": HTMLBeesButtonElement;
        "bees-button-group": HTMLBeesButtonGroupElement;
        "bees-config-provider": HTMLBeesConfigProviderElement;
        "bees-layout": HTMLBeesLayoutElement;
        "bees-layout-content": HTMLBeesLayoutContentElement;
        "bees-layout-footer": HTMLBeesLayoutFooterElement;
        "bees-layout-header": HTMLBeesLayoutHeaderElement;
        "bees-layout-sider": HTMLBeesLayoutSiderElement;
        "bees-locale-provider": HTMLBeesLocaleProviderElement;
        "bees-space": HTMLBeesSpaceElement;
        "bees-spin": HTMLBeesSpinElement;
    }
}
declare namespace LocalJSX {
    interface BeesButton {
        "beeTitle"?: string;
        "block"?: boolean;
        "danger"?: boolean;
        "disabled"?: boolean;
        "ghost"?: boolean;
        "href"?: string;
        "htmlType"?: ButtonHTMLType;
        "icon"?: string;
        "loading"?: Loading;
        "onBeeClick"?: (event: BeesButtonCustomEvent<MouseEventHandler>) => void;
        "onBeeMousedown"?: (event: BeesButtonCustomEvent<MouseEventHandler>) => void;
        "prefixCls"?: string;
        "shape"?: ButtonShape;
        "size"?: SizeType;
        "target"?: string;
        "type"?: ButtonType;
    }
    interface BeesButtonGroup {
    }
    interface BeesConfigProvider {
        "componentSize"?: SizeType1;
        "locale": Locale;
        "theme": ThemeConfig;
    }
    interface BeesLayout {
        "beTagName"?: string;
        "hasSider"?: boolean;
        "prefixCls"?: string;
    }
    interface BeesLayoutContent {
        "beTagName"?: string;
        "hasSider"?: boolean;
        "prefixCls"?: string;
    }
    interface BeesLayoutFooter {
        "beTagName"?: string;
        "hasSider"?: boolean;
        "prefixCls"?: string;
    }
    interface BeesLayoutHeader {
        "beTagName"?: string;
        "hasSider"?: boolean;
        "prefixCls"?: string;
    }
    interface BeesLayoutSider {
        "breakpoint"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl';
        "collapsed"?: boolean;
        "collapsedWidth"?: number | string;
        "collapsible"?: boolean;
        "defaultCollapsed"?: boolean;
        "onBeesBreakpoint"?: (event: BeesLayoutSiderCustomEvent<{ broken: boolean }>) => void;
        "onBeesCollapse"?: (event: BeesLayoutSiderCustomEvent<{ collapsed: boolean; type: 'clickTrigger' | 'responsive' }>) => void;
        "prefixCls"?: string;
        "reverseArrow"?: boolean;
        "theme"?: 'light' | 'dark';
        "trigger"?: any;
        "width"?: number | string;
        "zeroWidthTriggerStyle"?: CSSProperties;
    }
    interface BeesLocaleProvider {
        "locale"?: Locale | undefined;
    }
    interface BeesSpace {
    }
    interface BeesSpin {
        "delay"?: number;
        "indicator"?: any;
        "prefixCls"?: string;
        "size"?: SpinSize;
        "spinning"?: boolean;
        "tip"?: any;
        "wrapperClassName"?: string;
    }
    interface IntrinsicElements {
        "bees-button": BeesButton;
        "bees-button-group": BeesButtonGroup;
        "bees-config-provider": BeesConfigProvider;
        "bees-layout": BeesLayout;
        "bees-layout-content": BeesLayoutContent;
        "bees-layout-footer": BeesLayoutFooter;
        "bees-layout-header": BeesLayoutHeader;
        "bees-layout-sider": BeesLayoutSider;
        "bees-locale-provider": BeesLocaleProvider;
        "bees-space": BeesSpace;
        "bees-spin": BeesSpin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bees-button": LocalJSX.BeesButton & JSXBase.HTMLAttributes<HTMLBeesButtonElement>;
            "bees-button-group": LocalJSX.BeesButtonGroup & JSXBase.HTMLAttributes<HTMLBeesButtonGroupElement>;
            "bees-config-provider": LocalJSX.BeesConfigProvider & JSXBase.HTMLAttributes<HTMLBeesConfigProviderElement>;
            "bees-layout": LocalJSX.BeesLayout & JSXBase.HTMLAttributes<HTMLBeesLayoutElement>;
            "bees-layout-content": LocalJSX.BeesLayoutContent & JSXBase.HTMLAttributes<HTMLBeesLayoutContentElement>;
            "bees-layout-footer": LocalJSX.BeesLayoutFooter & JSXBase.HTMLAttributes<HTMLBeesLayoutFooterElement>;
            "bees-layout-header": LocalJSX.BeesLayoutHeader & JSXBase.HTMLAttributes<HTMLBeesLayoutHeaderElement>;
            "bees-layout-sider": LocalJSX.BeesLayoutSider & JSXBase.HTMLAttributes<HTMLBeesLayoutSiderElement>;
            "bees-locale-provider": LocalJSX.BeesLocaleProvider & JSXBase.HTMLAttributes<HTMLBeesLocaleProviderElement>;
            "bees-space": LocalJSX.BeesSpace & JSXBase.HTMLAttributes<HTMLBeesSpaceElement>;
            "bees-spin": LocalJSX.BeesSpin & JSXBase.HTMLAttributes<HTMLBeesSpinElement>;
        }
    }
}
